#!/usr/bin/env bash
# Idempotent installer for claude-vault-capture.
# Safe: backs up files before modifying; validates JSON; uses marker-bounded blocks.
set -euo pipefail

# Resolve the repo from this script's own location, so the checkout can live anywhere.
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── Argument parsing ──────────────────────────────────────────────────────────
SMOKE=""
VAULT_ARG=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --smoke-test-mode) SMOKE="--smoke-test-mode"; shift ;;
        --vault) VAULT_ARG="${2:-}"; shift 2 ;;
        --vault=*) VAULT_ARG="${1#--vault=}"; shift ;;
        -h|--help)
            echo "Usage: ./install.sh [--vault PATH]"
            echo "  --vault PATH   Path to your Obsidian vault (else CAPTURE_VAULT_DIR, then prompt)."
            exit 0 ;;
        *) echo "Unknown argument: $1" >&2; exit 1 ;;
    esac
done

# ── Resolve the vault path ────────────────────────────────────────────────────
# Priority: --vault arg → CAPTURE_VAULT_DIR env → existing capture.env (idempotent
# re-run) → interactive prompt → error with guidance.
resolve_vault() {
    if [[ -n "$VAULT_ARG" ]]; then echo "$VAULT_ARG"; return; fi
    if [[ -n "${CAPTURE_VAULT_DIR:-}" ]]; then echo "$CAPTURE_VAULT_DIR"; return; fi
    if [[ -f "$CONFIG_FILE" ]]; then
        local existing
        existing="$(grep -E '^CAPTURE_VAULT_DIR=' "$CONFIG_FILE" | tail -1 | cut -d= -f2-)"
        existing="${existing%\"}"; existing="${existing#\"}"
        if [[ -n "$existing" ]]; then echo "$existing"; return; fi
    fi
    if [[ -t 0 ]]; then
        local default="$HOME/Obsidian" answer
        read -r -p "Path to your Obsidian vault [$default]: " answer
        echo "${answer:-$default}"
        return
    fi
    echo "ERROR: vault path not specified. Pass --vault PATH or set CAPTURE_VAULT_DIR." >&2
    exit 1
}

# ── Paths ─────────────────────────────────────────────────────────────────────
# Each FAKE_* fallback exists for the install smoke test (eval/run-install-smoke.sh),
# which redirects every write into temp dirs. FAKE_* is that harness's contract
# only: outside smoke mode a stray export must never redirect a real install.
if [[ "$SMOKE" != "--smoke-test-mode" ]]; then
    unset FAKE_HOME FAKE_VAULT FAKE_SETTINGS FAKE_START_DATE_PATH FAKE_CONFIG FAKE_GLOBAL_CLAUDE_MD
fi
CLAUDE_DIR="${FAKE_HOME:-$HOME}/.claude"
SETTINGS="${FAKE_SETTINGS:-$CLAUDE_DIR/settings.json}"
START_DATE_FILE="${FAKE_START_DATE_PATH:-$REPO/eval/state/start-date.txt}"
CONFIG_FILE="${FAKE_CONFIG:-$REPO/capture.env}"
GLOBAL_CLAUDE_MD="${FAKE_GLOBAL_CLAUDE_MD:-$CLAUDE_DIR/CLAUDE.md}"
if [[ "$SMOKE" == "--smoke-test-mode" ]]; then
    VAULT="${FAKE_VAULT:-$HOME/Obsidian}"
else
    VAULT="$(resolve_vault)"
fi

# Expand a leading ~ that the user may have typed at the prompt (read does not).
VAULT="${VAULT/#\~/$HOME}"

# The hook script is registered with its absolute resolved path (no $HOME/shell
# expansion ambiguity at hook-execution time).
HOOK_CMD="$REPO/hooks/session-end-capture.sh"

# ── 0. Write per-user runtime config ──────────────────────────────────────────
# Only CAPTURE_VAULT_DIR is managed here; any extra lines a user added (e.g.
# CAPTURE_USE_SUBSCRIPTION=1) are carried over so a re-run never wipes them.
{
    echo "# Generated by install.sh — per-user runtime config for claude-vault-capture."
    echo "# Sourced by hooks/session-end-capture.sh. Gitignored; safe to edit."
    echo "# Re-running install.sh refreshes CAPTURE_VAULT_DIR and preserves other lines."
    echo "CAPTURE_VAULT_DIR=\"$VAULT\""
    if [[ -f "$CONFIG_FILE" ]]; then
        # Carry over user-added assignments; drop our managed key, comments, blanks.
        grep -vE '^[[:space:]]*(#|CAPTURE_VAULT_DIR=|$)' "$CONFIG_FILE" || true
    fi
} > "${CONFIG_FILE}.tmp"
mv "${CONFIG_FILE}.tmp" "$CONFIG_FILE"
echo "Wrote config: $CONFIG_FILE (CAPTURE_VAULT_DIR=$VAULT)"

# ── 1. Create required directories ───────────────────────────────────────────
# Path B (Inbox/raw/) retired 2026-06-04 — capture is single-path into Inbox/auto/.
echo "Creating directories..."
mkdir -p "$VAULT/Inbox/auto" "$VAULT/claude-docs"
mkdir -p "$REPO/eval/state"
mkdir -p "$REPO/eval/fixtures/expected"

# ── 2. Eval state gitignore ───────────────────────────────────────────────────
EVAL_GITIGNORE="$REPO/eval/.gitignore"
if ! grep -qxF 'state/' "$EVAL_GITIGNORE" 2>/dev/null; then
    echo 'state/' >> "$EVAL_GITIGNORE"
    echo "Added state/ to eval/.gitignore"
fi

# ── 3. Register SessionEnd hook in settings.json ─────────────────────────────
echo "Updating $SETTINGS..."
mkdir -p "$(dirname "$SETTINGS")"
if [[ ! -f "$SETTINGS" ]]; then
    echo '{"hooks": {"SessionEnd": []}}' > "$SETTINGS"
fi

# Backup, restored below if the registration itself fails (the only step that
# can leave the file half-written).
cp "$SETTINGS" "${SETTINGS}.bak"

if ! python3 - "$SETTINGS" "$HOOK_CMD" <<'PYEOF'
import json, sys

settings_path = sys.argv[1]
hook_cmd = sys.argv[2]

with open(settings_path) as f:
    data = json.load(f)

data.setdefault("hooks", {}).setdefault("SessionEnd", [])
hooks = data["hooks"]["SessionEnd"]

# New format: {"matcher": "", "hooks": [{"type": "command", "command": "..."}]}
# Idempotency: remove any existing entry whose inner command matches ours.
def _is_our_entry(h):
    inner = h.get("hooks", [])
    return any(c.get("command") == hook_cmd for c in inner if isinstance(c, dict))

hooks[:] = [h for h in hooks if not _is_our_entry(h)]
hooks.append({
    "matcher": "",
    "hooks": [{"type": "command", "command": hook_cmd}]
})

with open(settings_path, "w") as f:
    json.dump(data, f, indent=2)
    f.write("\n")
PYEOF
then
    echo "ERROR: hook registration failed — restoring settings.json backup" >&2
    cp "${SETTINGS}.bak" "$SETTINGS"
    exit 1
fi
echo "Hook registered in settings.json"

VAULT_SAVE_PATCH="$REPO/skill-patches/vault-save.md"
VAULT_SAVE_TRIGGER_PATCH="$REPO/skill-patches/global-claude-md.vault-save-trigger.md"

# ── 4. Install / update vault-save skill ─────────────────────────────────────
# The patch IS the full skill file, so every run overwrites the whole file. Its
# YAML frontmatter must stay at byte 0 for Claude Code to parse the skill
# description — never wrap the file in additional markers. Patch files carry
# __VAULT_DIR__ / __REPO_DIR__ placeholders resolved to this user's paths.
if [[ -f "$VAULT_SAVE_PATCH" ]]; then
    VAULT_SAVE_SKILL="$CLAUDE_DIR/skills/vault-save/SKILL.md"
    mkdir -p "$(dirname "$VAULT_SAVE_SKILL")"
    vault_save_content="$(<"$VAULT_SAVE_PATCH")"
    vault_save_content="${vault_save_content//__VAULT_DIR__/$VAULT}"
    vault_save_content="${vault_save_content//__REPO_DIR__/$REPO}"
    printf '%s\n' "$vault_save_content" > "$VAULT_SAVE_SKILL"
    echo "Installed vault-save skill at $VAULT_SAVE_SKILL"
else
    echo "WARNING: $VAULT_SAVE_PATCH not found — skipping vault-save skill creation"
fi

# ── 5. Inject vault-save auto-trigger into global ~/.claude/CLAUDE.md ─────────
if [[ -f "$VAULT_SAVE_TRIGGER_PATCH" ]]; then
    touch "$GLOBAL_CLAUDE_MD"

    BEGIN_MARKER="<!-- BEGIN claude-vault-capture: vault-save-trigger -->"
    END_MARKER="<!-- END claude-vault-capture: vault-save-trigger -->"
    TRIGGER_CONTENT=$(<"$VAULT_SAVE_TRIGGER_PATCH")

    cp "$GLOBAL_CLAUDE_MD" "${GLOBAL_CLAUDE_MD}.bak"

    # Replace the existing marker block, or append one on first install.
    python3 - "$GLOBAL_CLAUDE_MD" "$BEGIN_MARKER" "$END_MARKER" "$TRIGGER_CONTENT" <<'PYEOF'
import sys, re
path, begin, end, content = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]
text = open(path).read()
new_block = f"{begin}\n{content}\n{end}"
if begin in text:
    pattern = re.escape(begin) + r".*?" + re.escape(end)
    updated = re.sub(pattern, new_block, text, flags=re.DOTALL)
else:
    separator = "\n" if text.endswith("\n") else "\n\n"
    updated = text + separator + new_block + "\n"
open(path, "w").write(updated)
PYEOF
    echo "Injected vault-save trigger into $GLOBAL_CLAUDE_MD"
else
    echo "WARNING: $VAULT_SAVE_TRIGGER_PATCH not found — skipping global CLAUDE.md update"
fi

# ── 6. Eval window anchor (first install only) ────────────────────────────────
if [[ ! -f "$START_DATE_FILE" ]]; then
    date +%Y-%m-%d > "$START_DATE_FILE"
    echo "Eval window started: $(cat "$START_DATE_FILE")"
fi

echo ""
echo "Install complete."
echo "  Hook:  $HOOK_CMD"
echo "  Vault: $VAULT"
echo "  State: $REPO/eval/state/"

# Friendly reminder: the hook runs $REPO/.venv/bin/python3, created by `uv sync`.
if [[ ! -x "$REPO/.venv/bin/python3" ]]; then
    echo ""
    echo "NOTE: $REPO/.venv/bin/python3 not found. Run 'uv sync' in $REPO so the"
    echo "      backgrounded worker has an interpreter, or captures will silently no-op."
fi
